version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
artifacts:
- path: '**/*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: 1EsewYvmcY1mezJgxG8QGZmrikfpIrr6AiyMuwckiPer+VobTN7xjjMvIN9h0sFd
  artifact: /.*\.nupkg/